export const validElementProps = [
  // Global attributes
  "id",
  "className",
  "style",
  "title",
  "lang",
  "dir",
  "tabIndex",
  "hidden",
  "accessKey",
  "contentEditable",
  "draggable",
  "spellCheck",
  "translate",
  "ref",

  // Form element attributes
  "name",
  "type",
  "value",
  "defaultValue",
  "checked",
  "defaultChecked",
  "placeholder",
  "required",
  "disabled",
  "readOnly",
  "multiple",
  "pattern",
  "min",
  "max",
  "step",
  "size",
  "cols",
  "rows",
  "autoComplete",
  "autoFocus",
  "form",
  "formAction",
  "formEncType",
  "formMethod",
  "formNoValidate",
  "formTarget",
  "maxLength",
  "minLength",
  "acceptCharset",
  "action",

  // Media element attributes
  "src",
  "alt",
  "crossOrigin",
  "poster",
  "preload",
  "autoPlay",
  "controls",
  "loop",
  "muted",
  "width",
  "height",
  "playsInline",
  "accept",

  // Anchor element attributes
  "href",
  "target",
  "download",
  "rel",
  "hrefLang",
  "type",

  // Image element attributes
  "srcSet",
  "sizes",
  "loading",
  "decoding",
  "useMap",

  // Table element attributes
  "colSpan",
  "rowSpan",
  "headers",
  "scope",

  // List element attributes
  "type", // for <ol> (ordered list)

  // Script and Link element attributes
  "async",
  "defer",
  "integrity",
  "crossOrigin", // for <script> and <link>

  // Meta element attributes
  "charset",
  "content",
  "httpEquiv",
  "name",
  "property",

  // Miscellaneous attributes
  "role",
  "aria-*",
  "data-*",
  "itemProp",
  "itemScope",
  "itemType",
  "itemID",
  "itemRef",
  "srcObject", // for <video> and <audio> elements
  "allowFullScreen", // for <iframe> elements
  "allow", // for <iframe> elements

  // motion props
  "animate",
  "initial",
  "exit",
  "variants",
  "whileHover",
  "whileTap",
  "whileDrag",
  "drag",
  "dragConstraints",
  "dragElastic",
  "dragMomentum",
  "dragPropagation",
  "dragTransition",
  "layout",
  "layoutId",
  "transition",
  "onAnimationStart",
  "onAnimationComplete",
  "onUpdate",
  "onDragStart",
  "onDragEnd",
  "onDrag",
  "onDirectionLock",
  "onDragTransitionEnd",
  "onHoverStart",
  "onHoverEnd",
  "onTapStart",
  "onTap",
  "onTapCancel",
  "onPointerDown",
  "onPointerUp",
  "onPan",
  "onPanStart",
  "onPanEnd",
  "onPanSessionStart",
  "onPanSessionEnd",
];
